service: client-experiments-lambda-at-edge

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 128
  timeout: 5

custom:
  cloudFrontDistributionId: YOUR_CLOUDFRONT_DISTRIBUTION_ID_GOES_HERE
  webpack:
    includeModules: true
    packager: "npm"

package:
  excludeDevDependencies: true
  exclude:
    - "node_modules/**"

plugins:
  - serverless-lambda-edge-pre-existing-cloudfront
  - serverless-webpack

functions:
  viewerRequest:
    handler: src/viewerRequest.handler
    role: LambdaIAMRole
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloudFrontDistributionId}
          eventType: viewer-request
          pathPattern: "*"
          includeBody: false
  viewerResponse:
    handler: src/viewerResponse.handler
    role: LambdaIAMRole
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloudFrontDistributionId}
          eventType: viewer-response
          pathPattern: "*"
          includeBody: false
  originRequest:
    handler: src/originRequest.handler
    role: LambdaIAMRole
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloudFrontDistributionId}
          eventType: origin-request
          pathPattern: "*"
          includeBody: false
  originResponse:
    handler: src/originResponse.handler
    role: LambdaIAMRole
    events:
      - preExistingCloudFront:
          distributionId: ${self:custom.cloudFrontDistributionId}
          eventType: origin-response
          pathPattern: "*"
          includeBody: false
          
resources:
  Resources:
    LambdaIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement: 
            - Effect: Allow
              Principal: 
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: ${self:service}-LambdaIAMPolicies
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:*"
                  Resource: "arn:aws:logs:*:*:*"